### PR TITLE
Add a short description to the readme

### PR DESCRIPTION
**Pull request by EwoutH**

### CODE REVIEW

**Comment by EwoutH** [comment]
@thulle Could you review and merge this PR?

**Comment by EwoutH** [comment]
I'm doing some cleanup of old, open PRs. If you would like to get these changes in, please leave a reply or review.

In two weeks I will close this PR if no reaction received.

**Comment by EwoutH** [comment]
Closing due to lack of response.

**Comment by thulle** [comment]
Sorry, totally missed this. Can't seem to merge it when it's closed, if you reopen I'll merge. I'll take a look on why stats are broken again too.. site prob. broke youtube-dl again.

**Comment by EwoutH** [comment]
No worries, thanks for getting back!

**Comment by thulle** [comment]
Seems like it corrupted its own cookie file and thus didn't manage to run again. I had made it so it would save the playlist data so I could backfill stats in the case of the script not managing to extract them, but erroring out on the cookie file made it so the playlist wasn't pulled at all.
The youtube-dl fork yt-dlp had a nice auto-update feature though, so I added a version check in the script, so hopefully we should be able to avoid youtube updates breaking the stats for too long in the future.

**Comment by EwoutH** [comment]
Awesome!

It's interesting that we now have this data over such an extended period of time.

Ideally we also want to log the max resolution of each video. Because then we can calculate the percentage AV1 for each resolution.

**Pull request merged**
